export enum WorkflowType {
  AiChat = 'ai-chat-node',
  Application = 'application-node',
  Base = 'base-node',
  Condition = 'condition-node',
  DataSourceLocalNode = 'data-source-local-node',
  DataSourceWebNode = 'data-source-web-node',
  DocumentExtractNode = 'document-extract-node',
  DocumentSplitNode = 'document-split-node',
  FormNode = 'form-node',
  ImageGenerateNode = 'image-generate-node',
  ImageToVideoGenerateNode = 'image-to-video-node',
  ImageUnderstandNode = 'image-understand-node',
  IntentNode = 'intent-node',
  KnowledgeBase = 'knowledge-base-node',
  KnowledgeWriteNode = 'knowledge-write-node',
  LoopBodyNode = 'loop-body-node',
  LoopBreakNode = 'loop-break-node',
  LoopContinueNode = 'loop-continue-node',
  LoopNode = 'loop-node',
  LoopStartNode = 'loop-start-node',
  McpNode = 'mcp-node',
  ParameterExtractionNode = 'parameter-extraction-node',
  Question = 'question-node',
  Reply = 'reply-node',
  RerankerNode = 'reranker-node',
  SearchDocument = 'search-document-node',
  SearchKnowledge = 'search-knowledge-node',
  SpeechToTextNode = 'speech-to-text-node',
  Start = 'start-node',
  TextToSpeechNode = 'text-to-speech-node',
  TextToVideoGenerateNode = 'text-to-video-node',
  ToolBaseNode = 'tool-base-node',
  ToolLib = 'tool-lib-node',
  ToolLibCustom = 'tool-node',
  ToolStartNode = 'tool-start-node',
  ToolWorkflowLib = 'tool-workflow-lib-node',
  VariableAggregationNode = 'variable-aggregation-node',
  VariableAssignNode = 'variable-assign-node',
  VariableSplittingNode = 'variable-splitting-node',
  VideoUnderstandNode = 'video-understand-node',
}

export enum WorkflowKind {
  DataSource = 'data-source',
}

export enum WorkflowMode {
  Application = 'application',
  ApplicationLoop = 'application-loop',
  Knowledge = 'knowledge',
  KnowledgeLoop = 'knowledge-loop',
  Tool = 'tool',
  ToolLoop = 'tool-loop',
}
